{
    'name': 'Micro Abrasive Preset Reports',
    'version': '12.0.1.0.0',
    'summary': 'Micro Abrasive Reports',
    'description': 'Micro Abrasive Preset Reports',
    'category': 'Sales Commission',
    'author': 'Howk-i ERP Zone - Simplified',
    'website': 'http://erp.howk-i.com/',
    'support': 'nirmalraj.erp@gmail.com',
    'license': 'AGPL-3',
    'depends': ['sale', 'account', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/customer_status_view.xml',
        'wizard/invoice_customer_details.xml',
        'reports/customer_status_report_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
